---
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  tags:
    - skip_ansible_lint

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)$'
    replace: '# \1'

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Let iptables see bridged traffic
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - { name: net.bridge.bridge-nf-call-iptables, value: 1}

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Disable SELinux
  selinux:
    state: disabled
